### ISSUE TITLE
feat: 시스템 엔티티(@sys.*) 구현

### ISSUE THREAD

**Issue by riyenas0925** [ossmini/Kakao_I_OpenBuilder_Library#32]
### 구현 목표
* 카카오 챗봇의 시스템 엔티티를 구현한다.
* 시스템이 자동으로 생성한 포맷에 맞는 엔티티만 지원한다.

<img width="823" alt="스크린샷 2022-04-10 오후 1 38 55" src="https://user-images.githubusercontent.com/32615702/162601763-7dfe276f-8ab7-400f-8978-0206fdbbbada.png">

#### 챗봇
* 시스템 엔티티: @sys.date.period (챗봇에 정의)

#### 라이브러리 코드 예시 
* enum: 시스템 엔티티에서 @와 sys를 제거하거 대문자 파스칼 케이스로 변환 (DATE_PERIOD)
* parameter: 시스템 엔티티에서 @를 제거하고 소문자 스네이크 케이스로 변환 (sys_date_period)

> 패키지 위치 : dev.mini.kakaoiopenbuilder.skill.util로 생성
> 아래의 예시는 전체 55개 중 3개를 구현한 예시
```java
package dev.mini.kakaoiopenbuilder.skill.util;

public enum SystemEntity {
    DATE("sys_date"),
    DATE_PERIOD("sys_date_period"),
    DATE_LUNAR("sys_date_lunar");

    private final String parameter;

    SystemEntity(String parameter) {
        this.parameter = parameter;
    }

    public String getParameter() {
        return parameter;
    }

}
```

아래와 같이 사용할 수 있게끔 구현
```
SystemEntity.DATE_PERIOD.getParameter(); // "sys_date_period 반환"
```

### 구현 목록 (55개)
엔티티명 | 설명 | 예시 | 발화 예시
-- | -- | -- | --
@sys.date | '날짜'에 해당하는 엔티티를 태깅합니다. | 오늘, 내일, 어제, 2018년 1월15일, 1월 1일, 수요일 | 오늘 뉴스 들려줘1월 1일은 무슨 요일이야
@sys.date.period | 날짜 중에서 '기간 범위'에 해당하는 엔티티를 태깅합니다. | 이번주, 올해, 주말, 2019년, 1월, 1일부터 10일까지 | 이번주 사수자리 운세 알려줘올해 무슨 해야
@sys.date.lunar | 날짜 중에서 '음력'에 해당하는 엔티티를 태깅합니다. | 음력 1월1일, 음력 2019년 5월 5일, 올해 음력 5월 16일, 음력 설날 | 음력 1월 1일이 언제야음력 2019년 5월 5일 양력으로 며칠이야
@sys.date.period.lunar | 날짜 중에서 '음력 기간'에 해당하는 엔티티를 태깅합니다. | 음력 1월, 음력 6월, 음력 8월 | 정월은 음력 1월을 말합니다음력 8월은 음력에서 여덟 번째 달이다
@sys.time | '시간'에 해당하는 엔티티를 태깅합니다.※시간흐름에 따른 date 정보 속성값도 포함됨 | 30분, 7시, 10분 뒤, 오전 6시, 30초, 정오 | 7시 알람 맞춰줘알람 정오 지워줘
@sys.time.period | 시간 중에서 '시간대'에 해당하는 엔티티를 태깅합니다.※시간흐름에 따른 date 정보 속성값도 포함됨 | 오전, 아침, 새벽, 저녁, 1시부터 2시까지 | 오전 알람 삭제해줘아침 뉴스 틀어줘
@sys.date.time | 날짜 중에서 '날짜와 시간' 조합에 해당하는 엔티티를 태깅합니다. | 내일 7시, 현재, 모레 오후 11시, 내일 오전 7시, 오늘 1시, 1월1일 오후 2시 | 내일 7시 알람 맞춰줘현재 상영작 알려줘
@sys.date.time.period | 날짜 중에서 '기간 범위와 시간' 조합에 해당하는 엔티티를 태깅합니다. | 오늘 낮, 내일 오전, 모레 오후, 어젯밤, 월요일 오후, 오늘 1시부터 2시까지, 1월1일 9시부터 10시 | 오늘 낮 날씨 어때내일 오전 알람 꺼
@sys.number | '숫자'에 해당하는 엔티티를 태깅합니다. | 1, 삼, 다섯, 열명, 30개 | 삼 더하기 삼볼륨 다섯 키 낮춰 줘
@sys.number.times | 숫자 중에서 '회차'에 해당하는 엔티티를 태깅합니다. | 11회차, 40회, 1화, 2부, 1편, 3차, 834회 | 미우새 1부 틀어줘로또 당첨 번호 제 834회 알려줘
@sys.number.percent | 숫자 중에서 '퍼센트'에 해당하는 엔티티를 태깅합니다. | 20퍼센트, 30프로, 백퍼센트, 50% | 블라인드 20퍼센트 정도 열어줘블라인드 30프로만 내려줘
@sys.number.ordinal | 숫자 중에서 '순서'에 해당하는 엔티티를 태깅합니다. | 1번, 첫 번째, 열 번째, 백 번째 | 플레이리스트 1번 틀어줘네 번째 playlist 재생
@sys.number.age | 숫자 중에서 '나이'에 해당하는 엔티티를 태깅합니다. | 1살, 18세, 스무살, 20세 | 내 아이는 1살입니다스무살에 대학에 입학했어요
@sys.number.birthyear | 숫자 중에서 '출생년도'에 해당하는 엔티티를 태깅합니다. | 1995년생, 85년생, 72년도생 | 1996년생 운세 알려줘87년생 운세 알려줘
@sys.number.decade | 숫자 중에서 '년대(~년대)'에 해당하는 엔티티를 태깅합니다. | 1900년대, 2000년대, 80년대, 90년대 | 90년대 인기 팝 들려줘1990년대 발라드 틀어줘
@sys.number.album | 숫자 중에서 '앨범(~집)'에 해당하는 엔티티를 태깅합니다. | 1집, 2집, 3집, 10집 | winner 2집 재생해줘자우림 10집 틀어줘
@sys.number.rank | 단위 중에서 '순위'에 해당하는 엔티티를 태깅합니다. | 1위, 100위, 1등 | 실시간 이슈 10위 알려줘멜론 차트 10위부터 틀어줘
@sys.unit.duration | 단위 중에서 '기간/시간'을 의미하는 엔티티를 태깅합니다. | 1시간, 1시간 반, 1개월, 4주, 일주일, 이주일, 5년 2개월, 5개월, 5개월 20일, 이틀, 30분 동안, 3일동안, 4분 30초동안 | 1시간 타이머 시작빗소리 10분 동안 틀어줘
@sys.unit.length | 단위 중에서 '길이'에 해당하는 엔티티를 태깅합니다. | 5mm, 1cm, 10cm, 1m, 1km, 100km, 1야드, 100피트, 20인치, 1마일 | 1m 간격으로 앉아주세요서울부터 부산까지 거리는 325km입니다
@sys.unit.area | 단위 중에서 '넓이'에 해당하는 엔티티를 태깅합니다. | 1제곱미터, 25m², 100km², 1헥타아르, 200헥타아르, 1yd², 200ft², 25평, 30에이커 | 서울의 면적은 605.2km²입니다152 제곱미터는 몇 제곱킬로미터입니까
@sys.unit.weight | 단위 중에서 '무게'에 해당하는 엔티티를 태깅합니다. | 1g, 1kg, 10kg, 100mg, 100g, 1톤, 100파운드, 10온스, 7그레인, 1돈, 1근, 10냥, 10관 | 1kg 상자에 넣어주세요금 1돈은 정확히 3.75 그램입니다.
@sys.unit.volume | 단위 중에서 '부피'에 해당하는 엔티티를 태깅합니다. | 1세제곱미터, 1cc, 10ml, 500ml, 10데시리터, 1리터, 100cc, 1갤론, 100cm³, 10m³, 10in³, 10ft³, 1yd³, 1홉, 1되, 1말 | 물 1세제곱미터는 약 1 톤 물의 중량이다1cc는 0.001 리터를 의미한다
@sys.unit.pressure | 단위 중에서 '압력'에 해당하는 엔티티를 태깅합니다. | 1기압, 20프사이, 20파스칼, 20헥토파스칼, 20킬로파스칼, 20메가파스칼, 100밀리바, 100바, 1수은주밀리미터, 1mmH₂O, 10inHg, 10inchH₂O | 1기압은 몇 파스칼입니까?1bar는 100kPa 입니다.
@sys.unit.temperature | 단위 중에서 '온도'에 해당하는 엔티티를 태깅합니다. | 17°c, 20도, 33.8°f | 거실 난방 20도로 맞춰줘거실 난방 온도 22도로 맞춰줘
@sys.unit.speed | 단위 중에서 '속도'에 해당하는 엔티티를 태깅합니다. | 100m/s, 1마하, 10km/h, 1knot | 100m/s는 0.1km/s 입니다10000km/h는 8.17마하입니다..
@sys.unit.data | 단위 중에서 '정보(데이터량)'에 해당하는 엔티티를 태깅합니다. | 1바이트, 100기가바이트, 100GB, 1TB | 1바이트는 8비트 입니다1TB는 1024GB입니다.
@sys.unit.energy | 단위 중에서 '에너지 단위'에 해당하는 엔티티를 태깅합니다. | 1헤르츠, 1킬로헤르츠, 1메가헤르츠, 1기가헤르츠, 100데시벨, 10ampre, 10암페어, 10마력 | 1Mhz는 1000kHz 입니다
@sys.unit.currency | 단위 중에서 '통화'에 해당하는 엔티티를 태깅합니다. | 천원, 5천원, 1달러, 100엔, 100위안, 1유로, 오백 파운드, 1파운드, 10프랑, 10센트 | 1달러 환율이 어떻게 돼?1파운드가 한화로 얼마야
@sys.text | 되묻기 상황에서 '유저가 입력한 문장 전체'를 태깅합니다. |   |  
@sys.location | 지역 중에서 '국내 지역'에 해당하는 엔티티를 태깅합니다. | 제주도, 강원도, 서울, 송파구, 잠실동 | 제주도 날씨 알려줘내일 강원도 날씨
@sys.nation | '국가명'에 해당하는 엔티티를 태깅합니다. | 대한민국, 프랑스, 일본, 영국, 미국 | 1월 7일 대한민국 날씨 알려줘지금 프랑스 파리 몇시야?
@sys.state | 지역 중에서 '해외 주 단위'에 해당하는 엔티티를 태깅합니다. | 캘리포니아, 버몬트, 뉴저지, 콜로라도 | 지금 캘리포니아 몇 시야미국 뉴저지 시간은 어떻게 돼요
@sys.city | 지역 중에서 '해외도시명'에 해당하는 엔티티를 태깅합니다. | 뉴욕, 도쿄, 워싱턴 D.C., 베이징, 런던 | 오늘 뉴욕 날씨 좋아?워싱턴 D.C.와 베이징의 시차 알려줘
@sys.fortune.starsign | '별자리 이름'에 해당하는 엔티티를 태깅합니다. | 물병자리, 물고기자리, 게자리 | 이번주 물병자리 운세 알려줘1월 이달의 사자자리 운세 어때
@sys.fortune.zodiac | '띠 이름'에 해당하는 엔티티를 태깅합니다. | 돼지띠, 쥐띠, 소띠 | 이번주 돼지띠 운세 알려줘토끼띠는 몇 년생이야
@sys.person.name | '인물 : 개인'에 해당하는 엔티티를 태깅합니다. | 아이유, 박지성, 김광석 | 아이유 인기곡 들려줘박지성에 대해서 알려줘
@sys.person.group | '인물 : 그룹명'에 해당하는 엔티티를 태깅합니다. | 엑소, exo, 퀸, queen, 블랙핑크, blackpink, 방탄소년단, bts | 방탄소년단 최신 앨범 틀어줘퀸 1991년 앨범 틀어줘
@sys.currencyname | '통화명'에 해당하는 엔티티를 태깅합니다. | 달러, 엔, 유로, 오스트레일리아달러, 베트남동, 파운드 | 미국의 통화는 달러입니다영국의 화폐단위는 파운드입니다.
@sys.currency.code | '통화 코드'에 해당하는 엔티티를 태깅합니다. | USD, JPY, EUR, AUD, VND, GBP, ZWD | 일본 화폐인 '엔'의 통화코드는 JPY입니다.
@sys.sports.name | 스포츠 정보 중에서 '종목명'에 해당하는 엔티티를 태깅합니다. | 야구, 축구, 태니스, 태권도 | 오늘 축구 경기 있어?내일 야구 일정 알려줘
@sys.sports.league | 스포츠 정보 중에서 '리그명'에 해당하는 엔티티를 태깅합니다. | 프리미어리그, NBA, KBO리그, mlb | 작년 프리미어리그 순위 알려줘이번달 KBO리그 경기 있어?
@sys.sports.team | 스포츠 정보 중에서 '팀명'에 해당하는 엔티티를 태깅합니다. | 리버플, 토트넘, 맨체스터 유나이티드, KIA 타이거즈 | 2018년 1월15일 리버풀 경기 알려줘토트넘 경기에 손흥민 나왔어?
@sys.sports.stadium | 스포츠 정보 중에서 '경기장'에 해당하는 엔티티를 태깅합니다. | 잠실 종합 운동장 야구장, 수원 월드컵 경기장, 대구 스타디움, 문학 경기장 | 상암월드컵 경기장 축구 경기 있어?대구 스타디움 경기장 오늘 일정 없어?
@sys.tv.name | TV 정보 중에서 '프로그램명'에 해당하는 엔티티를 태깅합니다. | 무한도전, 라디오 스타, 런닝맨 | 오늘 라디오 스타에 누구 나와?런닝맨 멤버 알려줘
@sys.tv.channelname | TV 정보 중에서 '채널명'에 해당하는 엔티티를 태깅합니다. | tvn, mbc, kbs 1tv, ocn, jtbc | 지금 tvn에서 뭐 해?mbc 편성표 알려줘
@sys.radio.name | 라디오 정보 중에서 '프로그램명'에 해당하는 엔티티를 태깅합니다. | 음악캠프, 정오의 희망곡, 별이 빛나는 밤에, 정지영 라디오 | 배철수의 음악캠프에 나온 노래 들려줘정지영 라디오 선곡표 들려줘
@sys.radio.channelname | 라디오 정보 중에서 '채널명'에 해당하는 엔티티를 태깅합니다. | MBC FM 4u, SBS 러브FM, kbs1 라디오 | mbc fm 4u 틀어줘sbs 파워 fm 틀어줘
@sys.movie.name | 콘텐츠 정보 중에서 '영화명'에 해당하는 엔티티를 태깅합니다. | 신과 함께, 킹스맨, 어벤져스 인피니티 워 | 신과 함께 관객수 알려줘영화 킹스맨 장르 알려줘
@sys.organization.name | 콘텐츠 정보 중에서 '제작사'에 해당하는 엔티티를 태깅합니다. | 디즈니, 월트디즈니픽쳐스, 마블 스튜디오, 롯데엔터테인먼트 | 디즈니에서 제작한 영화 알려줘마블 스튜디오에서 만든 영화 뭐 있어?
@sys.theater.name | 콘텐츠 정보 중에서 '극장명'에 해당하는 엔티티를 태깅합니다. | CGV천호점, 메가박스, 롯데시네마 | cgv천호점 상영영화 알려줘메가박스 개봉작 알려줘
@sys.broadcast.name | 콘텐츠 정보 중에서 '방송사'에 해당하는 엔티티를 태깅합니다. | KBS, MBC, SBS, 극동방송, 불교방송 | 극동방송 틀어줘불교방송 틀어 주세요
@sys.url | 문장에서 'URL'에 해당하는 패턴을 태깅합니다. | https://www.kakaocorp.com, http://www.kakaocorp.com, www.kakaocorp.com | 카카오의 공식사이트는 https://www.kakaocorp.com 입니다.
@sys.bussiness.number | 문장에서 '사업자등록번호'에 해당하는 패턴을 태깅합니다. | 120-81-47521 | 카카오의 사업자등록번호는 120-81-47521 입니다.
@sys.phone.number | 문장에서 '전화번호'에 해당하는 패턴을 태깅합니다. | 010-1234-5678, 02-2456-7890 | 전화번호는 010-1234-5678 입니다.
@sys.licenseplate.number | 문장에서 '차량번호'에 해당하는 패턴을 태깅합니다. | 12 가 1234, 123 가 1234 | 차량번호는 12 가 1234 입니다.123 가 1234 번호가 제 차량입니다.

### Reference
https://i.kakao.com/docs/key-concepts-entity#%EC%97%94%ED%8B%B0%ED%8B%B0%EC%9D%98-%EA%B5%AC%EC%A1%B0

**Comment by donghwansuh** [comment]
@riyenas0925 issue #32 PR 하였으니 리뷰 부탁드립니다.
