### ISSUE TITLE
fix: pom.xml version 변경

### ISSUE THREAD

**Issue by riyenas0925** [ossmini/Kakao_I_OpenBuilder_Library#45]
## 버그 설명
현재 pom.xml에 0.0.0으로 버전이 설정되어 있습니다. 이것을 다음 릴리즈 버전인 1.0.1로 변경할 필요가 있습니다.

![image](https://user-images.githubusercontent.com/32615702/162743713-1dfc41f2-ae53-442d-ac23-ac28b1edbfcb.png)

**Comment by donghwansuh** [comment]
@riyenas0925 PR하였으니 검토 부탁드립니다.
